-- notes table seeds here (Example)
INSERT INTO notes (user_id, content, category_id) VALUES (2,'to watch movie RED', 3);
INSERT INTO notes (user_id, content, category_id) VALUES (1,'to buy spoon', 1);
INSERT INTO notes (user_id, content, category_id) VALUES (2, 'to read "Harry Potter"', 2);
INSERT INTO notes (user_id, content, category_id) VALUES (1, 'to eat pizza', 4);
INSERT INTO notes (user_id, content, category_id) VALUES (2, 'to watch documentary on climate change', 3);
INSERT INTO notes (user_id, content, category_id) VALUES (1, 'to buy groceries', 1);
INSERT INTO notes (user_id, content, category_id) VALUES (2, 'to read "The Great Gatsby"', 2);
INSERT INTO notes (user_id, content, category_id) VALUES (1, 'to eat sushi', 4);
INSERT INTO notes (user_id, content, category_id) VALUES (3, 'to watch TED talks', 3);
INSERT INTO notes (user_id, content, category_id) VALUES (1, 'to buy new shoes', 1);
INSERT INTO notes (user_id, content, category_id) VALUES (2, 'to read "To Kill a Mockingbird"', 2);
INSERT INTO notes (user_id, content, category_id) VALUES (3, 'to eat salad', 4);
INSERT INTO notes (user_id, content, category_id) VALUES (2, 'to watch cooking show', 3);
INSERT INTO notes (user_id, content, category_id) VALUES (1, 'to buy birthday present', 1);
INSERT INTO notes (user_id, content, category_id) VALUES (3, 'to read "1984"', 2);
INSERT INTO notes (user_id, content, category_id) VALUES (1, 'to eat ice cream', 4);
INSERT INTO notes (user_id, content, category_id) VALUES (2, 'to watch classic movies', 3);
INSERT INTO notes (user_id, content, category_id) VALUES (3, 'to buy new book', 1);
INSERT INTO notes (user_id, content, category_id) VALUES (3, 'to read "The Catcher in the Rye"', 2);
INSERT INTO notes (user_id, content, category_id) VALUES (1, 'to eat burgers', 4);
